# Generated by Django 4.2.30 on 2026-05-08 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_address', models.TextField()),
                ('customer_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('customer_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('food_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rain_rush_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('distance_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('UPI', 'UPI on Delivery'), ('ONLINE', 'Online (Razorpay)')], default='COD', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Collected'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('order_status', models.CharField(choices=[('PLACED', 'Placed'), ('ADMIN_REVIEWING', 'Admin Reviewing'), ('CONFIRMED_WITH_RESTAURANT', 'Confirmed With Restaurant'), ('PREPARING', 'Preparing'), ('DELIVERY_ASSIGNED', 'Delivery Assigned'), ('PICKED_UP', 'Picked Up'), ('ON_THE_WAY', 'On The Way'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PLACED', max_length=30)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_time', models.DecimalField(decimal_places=2, max_digits=8)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
